"""
END-TO-END WORKFLOW TEST - REAL API RESULTS
Research -> Document -> Email Draft

Tests the complete multi-agent workflow with REAL data
"""

import asyncio
import sys
import os
from datetime import datetime
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from dotenv import load_dotenv
load_dotenv()

from agents.researcher.researcher import create_researcher_agent

print("=" * 80)
print("END-TO-END WORKFLOW TEST - REAL API CALLS")
print("=" * 80)
print(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("=" * 80)

async def run_workflow():
    """Execute complete workflow"""

    # ====================
    # STEP 1: RESEARCH
    # ====================
    print("\n[STEP 1] RESEARCH - Using Researcher Agent")
    print("-" * 80)

    researcher = create_researcher_agent()
    research_query = "What is Google Agent Development Kit (ADK)? Explain its main features."

    print(f"Query: {research_query}")
    print(f"Agent: {researcher.name} (model: {researcher.model})")
    print("\nExecuting research...")

    start_time = datetime.now()
    research_result = await researcher.run(research_query)
    duration = (datetime.now() - start_time).total_seconds()

    print(f"\nResearch completed in {duration:.2f}s")
    print(f"Result length: {len(research_result)} characters")

    if len(research_result) < 200:
        print(f"\n[WARNING] Research result seems too short: {research_result}")
        print("\nTest failed - research didn't return proper results")
        return False

    # Save research result
    output_dir = Path("test_outputs")
    output_dir.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    research_file = output_dir / f"research_{timestamp}.txt"

    with open(research_file, 'w', encoding='utf-8') as f:
        f.write(research_result)

    print(f"Research saved to: {research_file}")

    # ====================
    # STEP 2: DOCUMENT
    # ====================
    print("\n[STEP 2] DOCUMENT CREATION")
    print("-" * 80)

    doc_content = f"""# Research Report: Google Agent Development Kit (ADK)

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Query:** {research_query}
**Research Duration:** {duration:.2f} seconds

---

## Research Findings

{research_result}

---

## Metadata

- **Research Agent:** {researcher.name}
- **Model:** {researcher.model}
- **Result Length:** {len(research_result)} characters
- **Sources:** Included in research findings above

---

*This report was automatically generated by the Google Workspace ADK Multi-Agent System.*
*Research Agent performed web search and synthesis using real APIs.*
"""

    doc_file = output_dir / f"report_{timestamp}.md"
    with open(doc_file, 'w', encoding='utf-8') as f:
        f.write(doc_content)

    doc_size = doc_file.stat().st_size
    print(f"Document created: {doc_file}")
    print(f"Document size: {doc_size} bytes")

    # ====================
    # STEP 3: EMAIL DRAFT
    # ====================
    print("\n[STEP 3] EMAIL DRAFT PREPARATION")
    print("-" * 80)

    # Extract first 300 chars for email preview
    preview = research_result[:300].replace('\n', ' ')
    if len(research_result) > 300:
        preview += "..."

    email_content = f"""TO: recipient@example.com
SUBJECT: Research Report - Google Agent Development Kit (ADK)
ATTACHMENT: {doc_file.name}

Hi,

I've completed the research on Google Agent Development Kit (ADK) as requested.

Key findings:
{preview}

Please find the complete research report attached.

Best regards,
Research Assistant

---
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Report file: {doc_file.name} ({doc_size} bytes)
"""

    email_file = output_dir / f"email_{timestamp}.txt"
    with open(email_file, 'w', encoding='utf-8') as f:
        f.write(email_content)

    print(f"Email draft created: {email_file}")

    # ====================
    # SUMMARY
    # ====================
    print("\n" + "=" * 80)
    print("WORKFLOW COMPLETED SUCCESSFULLY")
    print("=" * 80)

    print(f"\n✓ Step 1 - Research: {len(research_result)} chars in {duration:.2f}s")
    print(f"✓ Step 2 - Document: {doc_size} bytes saved to {doc_file.name}")
    print(f"✓ Step 3 - Email: Draft ready at {email_file.name}")

    print(f"\nGenerated files:")
    print(f"  1. {research_file} - Raw research data")
    print(f"  2. {doc_file} - Formatted report")
    print(f"  3. {email_file} - Email draft with attachment reference")

    print(f"\n[SUCCESS] Complete workflow executed with REAL API results!")
    print(f"[SUCCESS] All data is authentic from Google Search Grounding API")

    # Show preview of research
    print(f"\n" + "-" * 80)
    print("RESEARCH PREVIEW (first 400 chars):")
    print("-" * 80)
    print(research_result[:400] + "...\n")

    return True

if __name__ == "__main__":
    try:
        success = asyncio.run(run_workflow())
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"\n[ERROR] Workflow failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
