#!/usr/bin/env python3
"""Write a lock file recording the versions this machine is actually running.

`requirements-rpi.txt` declares ranges — 49 of them, all `>=`. That is right
for saying what the project needs, and wrong for reinstalling the Pi: pip is
free to resolve any newer version, so a rebuild months later can quietly pick
up different behaviour from the deployment that was working.

The fix is a lock file, and the only honest place to generate it is the
machine it is meant to reproduce. Versions resolved on a Windows dev box are
not the versions a Raspberry Pi will get — different wheels, different
architecture, sometimes different packages entirely.

So this is run ON the Pi:

    ssh pi
    cd ~/google_claude
    source .venv/bin/activate
    python scripts/freeze_requirements.py requirements-rpi.txt

and it writes `requirements-rpi.lock.txt` next to it. Reinstall with:

    pip install -r requirements-rpi.lock.txt

The lock covers the declared packages and everything they pulled in, because
a transitive dependency changing under you is the same problem wearing a
different hat.
"""

import argparse
import platform
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# Package name at the start of a requirements line, before any version spec,
# extras or environment marker.
_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def declared_packages(path: Path) -> list:
    """Package names named in a requirements file, comments skipped."""
    names = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "-")):
            continue
        match = _NAME.match(stripped)
        if match:
            names.append(match.group(1).lower().replace("_", "-"))
    return names


def installed() -> dict:
    """Everything pip can see, name -> version."""
    raw = subprocess.check_output(
        [sys.executable, "-m", "pip", "freeze", "--all"], text=True
    )
    versions = {}
    for line in raw.splitlines():
        if "==" not in line:
            continue  # editable installs and VCS pins are not lockable here
        name, _, version = line.partition("==")
        versions[name.strip().lower().replace("_", "-")] = version.strip()
    return versions


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "source", nargs="?", default="requirements-rpi.txt",
        help="the requirements file to lock (default: requirements-rpi.txt)",
    )
    parser.add_argument(
        "-o", "--output",
        help="where to write (default: <source> with .lock.txt)",
    )
    args = parser.parse_args()

    source = Path(args.source)
    if not source.exists():
        print(f"No such requirements file: {source}", file=sys.stderr)
        return 1

    output = Path(args.output) if args.output else source.with_suffix(".lock.txt")

    have = installed()
    declared = declared_packages(source)
    missing = [name for name in declared if name not in have]

    lines = [
        f"# Generated by scripts/freeze_requirements.py from {source.name}",
        f"# On: {platform.node()} ({platform.machine()}), "
        f"Python {platform.python_version()}",
        f"# At: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "#",
        "# These are the versions that machine was running and working with.",
        "# Regenerate on the same machine after a deliberate upgrade; do not",
        "# hand-edit, and do not generate it anywhere else — a lock from a",
        "# different architecture reproduces nothing.",
        "",
    ]
    for name in sorted(have):
        lines.append(f"{name}=={have[name]}")

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {output} ({len(have)} packages)")
    if missing:
        print(
            "\nDeclared but not installed here — the lock does not cover them:",
            file=sys.stderr,
        )
        for name in missing:
            print(f"  {name}", file=sys.stderr)
        print(
            "\nThat usually means this environment is not the one you meant "
            "to lock.",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
